CHANNEL_CONFIG = {
    1: {
        "nama":        "Sobat Antam",
        "voice":       "id-ID-ArdiNeural",
        "rate":        "+5%",
        "gaya":        "formal_analitis",
        "skema_warna": "merah_emas",
        "keywords_img": [
            "gold bar antam indonesia",
            "gold bullion bar close up",
            "antam logam mulia gold",
            "gold ingot stack shiny",
            "pure gold bar 999",
        ],
        "keywords_vid": [
            "gold bar shiny close up",
            "gold bullion bar",
            "pure gold ingot",
        ],
    },
    2: {
        "nama":        "Update Emas Harian",
        "voice":       "id-ID-GadisNeural",
        "rate":        "+3%",
        "gaya":        "santai_edukatif",
        "skema_warna": "biru_perak",
        "keywords_img": [
            "gold bar stack close up",
            "gold bullion investment",
            "gold ingot pile shiny",
            "antam gold bar indonesia",
            "gold bar texture macro",
        ],
        "keywords_vid": [
            "gold bar investment",
            "gold bullion close up",
            "gold ingot shiny",
        ],
    },
    3: {
        "nama":        "Info Logam Mulia",
        "voice":       "id-ID-ArdiNeural",
        "rate":        "-3%",
        "gaya":        "berita_singkat",
        "skema_warna": "hijau_platinum",
        "keywords_img": [
            "gold bar logam mulia",
            "gold bullion bar macro",
            "stacked gold ingot",
            "pure gold bar reflection",
            "gold bar vault storage",
        ],
        "keywords_vid": [
            "gold bar vault",
            "stacked gold bullion",
            "gold ingot macro",
        ],
    },
    4: {
        "nama":        "Harga Emas Live",
        "voice":       "id-ID-GadisNeural",
        "rate":        "+8%",
        "gaya":        "energik_motivatif",
        "skema_warna": "ungu_mewah",
        "keywords_img": [
            "gold bar luxury close up",
            "shiny gold bullion bar",
            "gold ingot premium",
            "gold bar collection",
            "antam gold bullion bar",
        ],
        "keywords_vid": [
            "luxury gold bar",
            "shiny gold bullion",
            "premium gold ingot",
        ],
    },
    5: {
        "nama":        "Cek Harga Emas",
        "voice":       "id-ID-ArdiNeural",
        "rate":        "+0%",
        "gaya":        "percakapan_akrab",
        "skema_warna": "oranye_tembaga",
        "keywords_img": [
            "gold bar antam close up",
            "gold bullion bar shiny",
            "gold ingot stack macro",
            "pure gold bar indonesia",
            "gold bar investment close",
        ],
        "keywords_vid": [
            "gold bar close up",
            "gold bullion stack",
            "gold ingot indonesia",
        ],
    },
}
